#!/bin/bash

mkdir experiments
mv data experiments
mv results experiments
mv *.py experiments
mv *.ipynb experiments
mv *.md experiments

mkdir datasets
mkdir datasets/movielens
mkdir datasets/amazon
mkdir datasets/amazon/meta

wget -P datasets/movielens/ http://files.grouplens.org/datasets/movielens/ml-1m.zip
wget -P datasets/amazon/ http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/ratings_Video_Games.csv
wget -P datasets/amazon/meta/ http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/meta_Video_Games.json.gz
